
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label opc;
	private global::Gtk.Label anio;
	private global::Gtk.Label nombre;
	private global::Gtk.Label id;
	private global::Gtk.Button button1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.opc = new global::Gtk.Label ();
		this.opc.Name = "opc";
		this.opc.LabelProp = global::Mono.Unix.Catalog.GetString ("OPCIONES");
		this.fixed1.Add (this.opc);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.opc]));
		w1.X = 481;
		w1.Y = 28;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.anio = new global::Gtk.Label ();
		this.anio.Name = "anio";
		this.anio.LabelProp = global::Mono.Unix.Catalog.GetString ("AÑO");
		this.fixed1.Add (this.anio);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.anio]));
		w2.X = 330;
		w2.Y = 30;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.nombre = new global::Gtk.Label ();
		this.nombre.Name = "nombre";
		this.nombre.LabelProp = global::Mono.Unix.Catalog.GetString ("NOMBRE");
		this.fixed1.Add (this.nombre);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.nombre]));
		w3.X = 157;
		w3.Y = 29;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.id = new global::Gtk.Label ();
		this.id.Name = "id";
		this.id.LabelProp = global::Mono.Unix.Catalog.GetString ("ID");
		this.fixed1.Add (this.id);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.id]));
		w4.X = 35;
		w4.Y = 25;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("mostrar");
		this.fixed1.Add (this.button1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button1]));
		w5.X = 522;
		w5.Y = 142;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 655;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button1.Activated += new global::System.EventHandler (this.OnButton1Activated);
	}
}
